openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  version: 1.0.11
servers:
  - url: https://localhost:8080/api/v1
tags:
  - name: Tfstate
    description: Api to control robot movements
paths:
  /tfstate:
    post:
      tags:
        - Tfstate
      summary: Send Terraform state file
      description: Send Terraform state
      operationId: postTfState
      requestBody:
        description: Send TF state
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TfPlanState'
        required: true
      responses:
        '200':
          description: Successful operation
        '401':
          description: Invalid ID supplied
        '404':
          description: Robot not found
        '405':
          description: Validation exception

    get:
      tags:
        - Tfstate
      summary: Get Terraform State
      description: Get Terraform State
      operationId: getTfstate
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TfPlanState'
        '401':
          description: Invalid ID supplied
        '404':
          description: Robot not found
        '405':
          description: Validation exception

components:
  schemas:
    TfPlanState:
      type: object
      additionalProperties: true
